server/app/routes/file_routes.py
import os
import uuid
from datetime import datetime, timedelta
from flask import Blueprint, flash, redirect
from flask import request, render_template, send_from_directory, abort, url_for, jsonify
from flask_login import login_required
from werkzeug.utils import secure_filename

from ..db import db
from ..config import UPLOADS_FOLDER
from flask_login import current_user

from ..models.file_upload import File, Upload
from ..models.user import User

from . import user_routes  # Import Blueprint instance from the main application package
from . import main_routes  # Import Blueprint instance from the main application package

from ..forms.file_forms import UploadForm, DownloadForm, UpdateForm

import zipfile

# Create a Blueprint for the file routes
file_routes = Blueprint('file_routes', __name__)


@file_routes.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    """
    This function handles file uploads. It accepts POST requests with files (one or many), an upload name, a message,
    expiration_hours, an optional password that means the upload will be password protected.
    """
    form = UploadForm()
    if request.method == 'POST':
        uploaded_files = request.files.getlist('file')
        # Check if the form is valid
        if form.validate_on_submit():
            # Get the form data
            message = form.message.data
            form.message.data = ''
            expiration_hours = form.expiration_hours.data
            upload_name = form.upload_name.data
            form.upload_name.data = ''
            password = form.password.data
            form.password.data = ''
            # Generate a unique ID for the upload
            upload_unique_id = str(uuid.uuid4())
            # Calculate the expiration time
            expires_at = datetime.utcnow() + timedelta(hours=int(expiration_hours))
            # Create a new Upload instance
            upload_obj = Upload(user_id=current_user.id,
                                unique_id=upload_unique_id,
                                upload_name=upload_name,
                                expires_at=expires_at,
                                message=message)
            print('Upload object created')
            if password:
                # If a password was provided, add it to the upload object
                upload_obj.password = password  # Upload object has receives passwords in this way to be hashed
                print('Added password to upload_object')
            db.session.add(upload_obj)  # Add the upload object to the session
            db.session.commit()  # Commit the session to the database

            for uploaded_file in uploaded_files:
                # Now we want to track what is inside the upload, what are the files
                if uploaded_file:
                    filename = secure_filename(uploaded_file.filename)  # Secure the filename, sanitisation!
                    unique_id = str(uuid.uuid4()) # Generate a unique ID for each file
                    # Create a filepath for the file using the unique ID
                    filepath = os.path.join(UPLOADS_FOLDER, unique_id)
                    uploaded_file.save(filepath)

                    # Keep same expiration time for all files in the upload

                    # Create a new File instance and associate it with the upload
                    file = File(filename=filename, unique_id=unique_id, expires_at=expires_at, upload_id=upload_obj.id)
                    # Add the file to the session
                    db.session.add(file)
                    print('File added to session')
            # Commit the session to the database, saving the files
            db.session.commit()
            flash('Upload completed successfully.', 'success')
            return redirect(url_for('file_routes.upload_success', unique_id=upload_obj.unique_id))
        flash('Form validation failed.', 'error')
    return render_template('upload.html',
                           is_pyqt='PyQt' in request.headers.get('User-Agent'),
                           form=form,
                           user_routes=user_routes,
                           file_routes=file_routes,
                           main_routes=main_routes)


@file_routes.route('/upload_success/<unique_id>', methods=['GET'])
@login_required
def upload_success(unique_id):
    """
    This function returns a page with the upload information and a link to download the files.
    """
    # Get the upload information from the database
    upload_info = Upload.query.filter_by(unique_id=unique_id).first_or_404()
    # Generate a download link for the upload, using the unique ID of the upload
    link = url_for('file_routes.download_file_page', unique_id=unique_id, _external=True)
    # Get the user details of the user who uploaded the file
    upload_user_id = upload_info.user_id
    # Get the user details of the user who uploaded the file
    user_user_details = User.query.get(upload_user_id)
    upload_info = {
        'upload_name': upload_info.upload_name,
        'message': upload_info.message,
        'expires_at': upload_info.expires_at,
        'upload_user': user_user_details
    }
    return render_template('upload_success.html',
                           link=link,
                           is_pyqt='PyQt' in request.headers.get('User-Agent'),
                           upload_info=upload_info,
                           file_routes=file_routes,
                           user_routes=user_routes,
                           main_routes=main_routes)


@file_routes.route('/update_upload/<unique_id>', methods=['GET', 'POST'])
@login_required
def update_upload(unique_id):
    """
    This function updates the upload information in the database.
    On GET requests, it returns a page with a form to update the upload information.
    On POST requests, it takes the new upload name, a message, and expiration time.
    """

    # Get the upload information from the database
    upload_record = Upload.query.filter_by(unique_id=unique_id).first_or_404()
    if current_user.id != upload_record.user_id:
        # Make sure the user trying to update the upload, is the owner of it
        flash("You don't have permission to update this upload", 'error')
        return redirect(url_for('main_routes.home'))
    # Create a form instance
    form = UpdateForm()
    #
    if request.method == 'POST':
        # Get the form data
        message = form.message.data
        form.message.data = ''
        upload_name = form.upload_name.data
        form.upload_name.data = ''
        expiration_hours = form.expiration_hours.data
        # Update the upload information in the database
        upload_record.upload_name = upload_name
        upload_record.message = message
        upload_record.expires_at = datetime.utcnow() + timedelta(hours=int(expiration_hours))
        # Commit the session to the database
        db.session.commit()

        flash("File updated successfully", 'success')
        return redirect(url_for('user_routes.profile'))

    return render_template('update_upload.html',
                           upload=upload_record,
                           form=form,
                           is_pyqt='PyQt' in request.headers.get('User-Agent'),
                           user_routes=user_routes,
                           file_routes=file_routes,
                           main_routes=main_routes)


@file_routes.route('/delete_upload/<unique_id>', methods=['GET', 'POST'])
@login_required
def delete_upload(unique_id):
    """
    This function deletes the upload and all its files from the database and the server.
    It being protected by the login_required decorator, it will only be accessible to logged-in users.
    """
    # Get the upload information from the database
    upload_record = Upload.query.filter_by(unique_id=unique_id).first_or_404()
    if current_user.id != upload_record.user_id:
        # Make sure the user trying to delete the upload, is the owner of it
        flash("You don't have permission to delete this upload", 'error')
        return redirect(url_for('main_routes.home'))
    print(f"Upload: {upload_record.upload_name}")
    if request.method == 'POST':
            # Delete the files from the server
        for file in upload_record.files:
            file_path = os.path.join(UPLOADS_FOLDER, file.unique_id)
            if os.path.isfile(file_path):
                os.remove(file_path)
        db.session.delete(upload_record)
        # Commit the session to the database
        db.session.commit()

        flash("Upload deleted successfully", 'success')
        return redirect(url_for('main_routes.home'))
    return render_template('delete_upload.html',
                           file=upload_record,
                           is_pyqt='PyQt' in request.headers.get('User-Agent'),
                           user_routes=user_routes,
                           file_routes=file_routes,
                           main_routes=main_routes)


@file_routes.route('/download/<unique_id>', methods=['GET', 'POST'])
def download_file_page(unique_id):
    """
    On GET, returns a page with the upload information and a form to download the files.
    On POST, it checks if the password is correct (if applicable) and serves the file for download.
    """
    # Get the upload information from the database
    upload_record = Upload.query.filter_by(unique_id=unique_id).first_or_404()
    upload_user_id = upload_record.user_id
    upload_user_details = User.query.get(upload_user_id)
    # Create a form instance
    form = DownloadForm()

    if request.method == 'POST':
        # If the upload is password protected, check if the password is correct
        if upload_record.is_password_protected():
            # Get the password from the form
            password = form.password.data
            form.password.data = ''
            # Verify the password

server/app/routes/main_routes.py
from flask import Blueprint, render_template, request, flash, jsonify

from . import user_routes  # Import Blueprint instance from the main application package
from . import file_routes  # Import Blueprint instance from the main application package

# Define a Blueprint for the main routes
main_routes = Blueprint('main_routes', __name__)


@main_routes.route('/')
def home():
    """
    Render the home page
    """
    return render_template('index.html',
                           file_routes=file_routes,
                           user_routes=user_routes,
                           main_routes=main_routes)


@main_routes.route('/about')
def about():
    """
    Render the about page
    """
    return render_template('about.html',
                           file_routes=file_routes,
                           user_routes=user_routes,
                           main_routes=main_routes)


@main_routes.route('/trigger_flash', methods=['POST'])
def trigger_flash():
    """
    Trigger a flash message
    """
    data = request.get_json()
    print(f'DATA: {data}')
    flash(data['message'], data['category'])
    return jsonify({'status': 'success'})

server/app/routes/user_routes.py
from flask import Blueprint, render_template, request, url_for, redirect, flash
from flask_login import login_required, logout_user, login_user, current_user

from ..models.user import User
from ..models.file_upload import File
from ..models.file_upload import Upload

from ..db import db

from ..forms.user_forms import SignUpForm, LoginForm

from . import file_routes  # Import Blueprint instance from the main application package
from . import main_routes  # Import Blueprint instance from the main application package

# Define a Blueprint for the user routes
user_routes = Blueprint('user_routes', __name__)


@user_routes.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        # If the user is already logged in, redirect to the profile page
        return redirect(url_for('user_routes.profile'))
    # Create a new instance of the signup form
    form = SignUpForm()
    if form.validate_on_submit():
        # Get form data
        name = form.name.data
        form.name.data = ''
        email = form.email.data
        form.email.data = ''
        password = form.password.data
        form.password.data = ''
        # Check if the email is already taken
        email_check = User.query.filter_by(email=email).first()  # Check if email already taken
        if email_check:
            # If the email is already taken, redirect to the signup page
            flash('Email already exists.', 'warning')
            return redirect(url_for('user_routes.signup'))
        # Create a new user
        new_user = User(name=name, email=email)
        # Set the password for this new user
        new_user.password = password
        # Add the new user to the database
        db.session.add(new_user)
        # Commit the changes to the database
        db.session.commit()
        flash('Account created successfully', 'success')
        return redirect(url_for('user_routes.login'))

    return render_template('signup.html',
                           form=form,
                           is_pyqt='PyQt' in request.headers.get('User-Agent'),
                           user_routes=user_routes,
                           file_routes=file_routes,
                           main_routes=main_routes)


@user_routes.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log the user in
    """
    if current_user.is_authenticated:
        # If the user is already logged in, redirect to the profile page
        return redirect(url_for('user_routes.profile'))
    # Create a new instance of the login form
    form = LoginForm()
    if form.validate_on_submit():
        # Get form data
        email = form.email.data
        form.email.data = ''
        password = form.password.data
        form.password.data = ''
        # Check if the user exists and the password is correct
        user = User.query.filter_by(email=email).first()

        if user and user.verify_password(password):
            login_user(user, remember=True)
            flash("Login successful!", 'success')
            return redirect(url_for(f'user_routes.profile'))
        else:
            flash("Incorrect credentials - Try again", 'error')

    else:
        return render_template('login.html',
                               form=form,
                               is_pyqt='PyQt' in request.headers.get('User-Agent'),
                               user_routes=user_routes,
                               file_routes=file_routes,
                               main_routes=main_routes)


@user_routes.route('/logout')
@login_required
def logout():
    """
    Log the current user out
    """
    logout_user()
    flash("You have been logged out", 'success')
    return redirect(url_for('main_routes.home'))


@user_routes.route('/profile', methods=['GET'])
@login_required
def profile():
    """
    Render the profile page
    """
    # Get all the uploads for the current user
    user_uploads = current_user.uploads
    return render_template('profile.html',
                           is_pyqt='PyQt' in request.headers.get('User-Agent'),
                           user_uploads=user_uploads,
                           user_routes=user_routes,
                           file_routes=file_routes,
                           main_routes=main_routes)

server/app/templates/about.html
{% extends "base.html" %}

{% block title %}File Upload App - About{% endblock %}

{% block content %}
<section class="container mx-auto">
    <h1 class="text-3xl font-bold mb-6">About <span class="underline">K.L.A.A.S</span></h1>
    <h2 class="text-xl font-semibold mb-4">The <span class="text-2xl">K</span>nowledge <span class="text-2xl">L</span>ookup and <span class="text-2xl">A</span>rchive <span class="text-2xl">A</span>ccess <span class="text-2xl">S</span>ystem</h2>

    <p class="mb-6">
        The File System Organiser is an advanced tool designed to streamline and enhance the organization and management
        of files on your computer. With our internal file system node model, once the file system is scanned it is
        cached and is loaded with each start up. Our model facilitates the searching of files and access of metadata from
        files without the need to address the file directly. This comprehensive solution offers a range of
        functionalities aimed at simplifying the way that users sort, store and share their digital content, making it
        an indispensable tool for both personal and professional use.
    </p>

    <h3 class="text-2xl font-semibold mb-4"><i class="px-3 fa-solid fa-list"></i>Key Features</h3>
    <ul class="list-none list-disc list-inside ml-6 text-base">
        <li class="">
            <i class="text-xl px-3 fa-solid fa-check"></i>
            <span class="font-semibold">File Sorting by Type:</span>
                The organiser automatically categorizes files into distinct folders based on their type, such as music, images, videos and documents.  Beyond basic sorting, the tool offers specialized organization options for various file types.
        </li>
        <li class="">
            <i class="text-xl px-3 fa-solid fa-check"></i><span class="font-semibold">Optimisation Features:</span> To maximise storage efficiency, the File System Organiser includes optimization features such as file compression and deduplication. Scheduled optimisations can be configured for convenience.
        </li>
        <li class="">
            <i class="text-xl px-3 fa-solid fa-check"></i><span class="font-semibold">Cloud Integration and Sharing:</span> A standout feature is its ability to upload files to our website, while generating shareable links. This function facilitates easy sharing of files with friends or colleagues, enhancing collaboration and accessibility.
         </li>
    </ul>
</section>
{% endblock %}

server/app/templates/base.html
<!DOCTYPE html>
<html lang="en"
      data-theme="nord" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}File Upload App{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/output.css') }}">
<!--    <link href="https://cdn.jsdelivr.net/npm/daisyui@2.47.0/dist/full.css" rel="stylesheet" type="text/css" />-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
<!--    <script src="https://cdn.jsdelivr.net/npm/daisyui@2.47.0/dist/themes.js" defer></script>-->
    <script src="https://kit.fontawesome.com/f0fc785b19.js" crossorigin="anonymous"></script>
<body class="bg-base">
    <!-- Navigation Bar -->
    <nav class="navbar bg-primary">
        <div class="navbar-start">
            <a href="{{ url_for('main_routes.home') }}" class="btn btn-ghost normal-case text-xl">K.L.A.A.S <i class="px-2 fa-solid fa-file"></i></a>
        </div>
        <div class="navbar-end">
            <div class="hidden sm:flex gap-2">
                <a href="{{ url_for('main_routes.about') }}" class="btn btn-ghost text-base">About</a>
                <a href="{{ url_for('file_routes.upload') }}" class="btn btn-ghost text-base">Upload</a>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('user_routes.profile') }}" class="btn btn-ghost  text-base">Profile</a>
                    <a href="{{ url_for('user_routes.logout') }}" class="btn btn-ghost text-base">Log Out</a>
                {% else %}
                    <a href="{{ url_for('user_routes.login') }}" class="btn btn-ghost text-base">Log In</a>
                {% endif %}
            </div>

            <div class="dropdown dropdown-end sm:hidden">
                <button class="btn btn-ghost">
                    <i class="fa-solid fa-bars text-lg"></i>
                </button>
                <ul tabindex="0" class="dropdown-content menu z-[1] bg-base-200 p-4 rounded-box shadow w-64 gap-2">
                    <li><a href="{{ url_for('main_routes.about') }}">About</a></li>
                    <li><a href="{{ url_for('file_routes.upload') }}">Upload</a></li>
                    {% if current_user.is_authenticated %}
                        <li> <a href="{{ url_for('user_routes.profile') }}">Profile</a></li>
                        <li> <a href="{{ url_for('user_routes.logout') }}">Log Out</a></li>
                    {% else %}
                        <li><a href="{{ url_for('user_routes.login') }}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mx-auto py-4">
        {% with messages = get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} shadow-lg mb-4" role="alert">
                        <h4 class="text-base font-light">{{ message }}</h4>
                        <button class="btn btn-sm btn-circle text-{{ category }}" aria-label="Close"
                                    onclick="this.parentNode.parentNode.remove()">✕</button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <div class="container mx-auto py-4 px-4 md:px-2">
        {% block content %}
        {% endblock %}
    </div>
    <script>
        function copyLinkToClipboard(buttonElement) {
            const link = buttonElement.dataset.link; // Extract link from data-link
            navigator.clipboard.writeText(link)
                .then(() => {
                    showFlashMessage('Message copied successfully', 'success')
                })
                .catch(() => {
                    console.error("Error copying to clipboard");
                });
        }

        function showFlashMessage(message, category) {
            fetch('/trigger_flash', {
                method: 'POST',
                body: JSON.stringify({message: message, category: category}),
                headers: { 'Content-Type': 'application/json' }
            })
                .catch(error => {
                    console.error("Error sending flash message:", error);
            });
        }
    </script>
</body>
</html>

server/app/templates/base_pyqt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/output.css') }}">
    <title>Login Page</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            overflow: hidden; /* Disables scroll */
            height: 100vh; /* 100% of the viewport height */
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: Arial, sans-serif; /* Sets the font for the whole page */
            background-color: rgb(245, 245, 245); /* Sets the background color */

        }
        /* Additional styles can go here */
    </style>
</head>

<body>
    <div class="container mx-auto py-4 px-4 md:px-2">
       {% block content %}
       {% endblock %}
    </div>
</body>
</html>

server/app/templates/profile.html
{% if is_pyqt %}
    {% extends "base_pyqt.html" %}
{% else %}
    {% extends "base.html" %}
{% endif %}

{% block title %}File Upload App - Profile{% endblock %}

{% block content %}
<h1 class="text-3xl font-semibold mb-4"><i class="px-3 fa-solid fa-user"></i>{{ current_user.name }}'s Profile</h1>

<p class="text-lg font-light"><i class="px-2 fa-solid fa-envelope"></i><span class="font-semibold">Email:</span> {{ current_user.email }}</p>

<h2 class="text-xl pt-4 font-bold">Uploaded Files</h2>
{% if user_uploads|length != 0 %}
    <div class="mt-6 py-2 rounded border border-r-black bg-gray-100 text-base-content"
        style="
            overflow-x: auto;
            overflow-y: hidden;
            white-space: nowrap;
        ">
       <table class="table table-compact w-full">
           <thead>
               <tr>
                   <th>Upload Name</th>
                   <th>Message</th>
                   <th>Contains</th>
                   <th>Expires At</th>
                   <th>Downloads</th>
<!--                   <th>Unique ID</th>-->
               </tr>
           </thead>
           <tbody class="font-light">
                   {% for upload in current_user.uploads %}
                       <tr>
                            <td>{{ upload.upload_name }}</td>
                            <td>{{ upload.message }}</td>
                            <td>
                               <ul>
                                   {% for file in upload.files %}
                                       <li>{{ file.filename }}</li>
                                   {% endfor %}
                               </ul>
                           </td>
                            <td>{{ upload.expires_at.strftime('%Y-%m-%d %H:%M') }}</td>
                            <td>{{ upload.download_count }}</td>
<!--                            <td>{{ upload.unique_id }}</td>-->
                            <td>
                                <button
                                   class="btn btn-sm bordered"
                                   data-link="{{ url_for('file_routes.download_file_page', unique_id=upload.unique_id, _external=True) }}"
                                   onclick="copyLinkToClipboard(this)"
                                >
                                    Copy <i class="fa-regular fa-copy"></i>
                                </button>
                                <a href="{{ url_for('file_routes.update_upload', unique_id=upload.unique_id) }}"
                                   class="btn btn-sm btn-secondary bordered">Update</a>
                                <a href="{{ url_for('file_routes.delete_upload', unique_id=upload.unique_id) }}"
                                   class="btn btn-sm btn-error bordered">Delete</a>
                            </td>
                       </tr>
                   {% endfor %}
           </tbody>
       </table>
    </div>
{% else %}
    <p class="text-base font-light py-1">You have not uploaded any files yet.</p>
{% endif %}
<h3 class="font-semibold text-lg py-2"> Upload a new file: </h3>
<div class="btn btn-md">
    <a href="{{ url_for('file_routes.upload') }}" class="text-sm py-1">Upload a file</a>
</div>

{% endblock %}

server/app/templates/profile_pyqt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    <style>
        body {
            margin: 0;
            padding: 0;
            overflow: hidden; /* Disables scroll */
            height: 100vh; /* 100% of the viewport height */
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: Arial, sans-serif; /* Sets the font for the whole page */
            background-color: rgb(245, 245, 245); /* Sets the background color */

        }
        /* Additional styles can go here */
    </style>
</head>
<body>

<h1 class="text-3xl font-semibold mb-4">{{ current_user.name }}'s Profile</h1>

<p><span class="font-semibold">Name:</span> {{ current_user.name }}</p>
<p><span class="font-semibold">Email:</span> {{ current_user.email }}</p>

<h2 class="text-xl pt-4 font-bold">Uploaded Files</h2>
{% if user_files|length != 0 %}
    <div class="mt-6 py-2 rounded border border-r-black bg-gray-100 text-base-content"
        style="
            overflow-x: auto;
            overflow-y: hidden;
            white-space: nowrap;
        ">
       <table class="table table-compact w-full">
           <thead>
               <tr>
                   <th>Filename</th>
                   <th>Message</th>
                   <th>Expires At</th>
                   <th>Downloads</th>
                   <th>Unique ID</th>
               </tr>
           </thead>
           <tbody class="font-light">
                   {% for file in user_files %}
                       <tr>
                            <td>{{ file.filename }}</td>
                            <td>{{ file.message }}</td>
                            <td>{{ file.expires_at.strftime('%Y-%m-%d %H:%M') }}</td>
                            <td>{{ file.download_count }}</td>
                            <td>{{ file.unique_id }}</td>
                            <td>
                                <a href="{{ url_for('file_routes.direct_download_file', unique_id=file.unique_id) }}"
                                   class="btn btn-sm bordered">Download</a>
                                <a href="{{ url_for('file_routes.update_file', unique_id=file.unique_id) }}"
                                   class="btn btn-sm btn-secondary bordered">Update</a>
                                <a href="{{ url_for('file_routes.delete_file', unique_id=file.unique_id) }}"
                                   class="btn btn-sm btn-error bordered">Delete</a>
                            </td>
                       </tr>
                   {% endfor %}
           </tbody>
       </table>
    </div>
{% else %}
    <p class="text-base font-light py-1">You have not uploaded any files yet.</p>
{% endif %}
<h3 class="font-medium text-lg py-2"> Upload a new file: </h3>
<div class="btn btn-md">
    <a href="{{ url_for('file_routes.upload') }}" class="text-sm py-1">Upload a file</a>
</div>
</body>
</html>
```

server/app/templates/update_upload.html
{% extends "base.html" %}

{% block title %}File Upload App - Update File{% endblock %}

{% block content %}
<div class="container mx-auto max-w-96">
    <h1 class="text-3xl font-semibold mb-4">Update file:  <span class="font-normal">{{ upload.filename }}</span></h1>
    <form action="{{ url_for('file_routes.update_upload', unique_id=upload.unique_id) }}" method="post" enctype="multipart/form-data">
        <div class="form-control mb-4">
            {{ form.upload_name.label(class="label label-text text-base font-semibold") }}
            {{ form.upload_name(class="input input-bordered rounded-md", value=upload.upload_name) }}
        </div>
        <div class="form-control mb-4">
            {{ form.message.label(class="label label-text text-base font-semibold") }}
            {{ form.message(class="textarea textarea-bordered text-sm", rows="1", value=upload.message) }}
        </div>
        <div class="form-control mb-4">
            {{ form.expiration_hours.label(class="label label-text text-base font-semibold") }}
            {{ form.expiration_hours(class="select select-bordered text-sm") }}
        </div>
        <button type="submit" class="btn btn-primary rounded-md">Update</button>
    </form>
</div>


{% endblock %}

server/app/templates/uploaded.html
{% if is_pyqt %}
    {% extends "base_pyqt.html" %}
{% else %}
    {% extends "base.html" %}
{% endif %}

{% block title %}Profile{% endblock %}

{% block content %}
    <h1>File Uploaded Successfully!</h1>
    <p>Your file "{{ file.filename }}" was uploaded successfully.</p>
    <p>Shareable link: <a href="{{ url_for('download_file_page', unique_id=file.unique_id, _external=True) }}">Click here</a></p>
    <!-- You can add an image or gif here to make the page more visually appealing -->
    <!-- ... -->

{% endblock %}